name: Lint and Test

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: self-hosted
    container:
      image: rust:1.87-bookworm
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup container environment
        run: |
          # Install required system dependencies
          apt-get update && apt-get install -y \
            build-essential \
            pkg-config \
            libssl-dev \
            git \
            curl \
            wget \
            ca-certificates \
            python3 \
            python3-pip

          # Install Rust components
          rustup component add rustfmt clippy llvm-tools-preview

          # Install cargo tools (note: most tools pre-installed in Docker image)
          # cargo install cargo-llvm-cov cargo-audit cargo-outdated cargo-deny

          # Install pre-commit
          pip3 install pre-commit

          # Set git safe directory
          git config --global --add safe.directory /github/workspace

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Check for compilation errors
        run: cargo check --all-targets --all-features

      - name: Run Clippy lints
        run: cargo clippy --all-targets --workspace --lib --examples --all-features --tests --benches -- -D warnings

      - name: Run tests
        run: cargo test --all-features --workspace

      - name: Run documentation tests
        run: cargo test --doc --all-features

      - name: Build examples
        run: cargo build --examples --all-features

      - name: Test examples compilation
        run: |
          cargo check --example accounts_example
          cargo check --example chains_example
          cargo check --example checkpoints_example
          cargo check --example network_examples
          cargo check --example states_example
          cargo check --example tokens_example
          cargo check --example transactions_example

  security-audit:
    name: Security Audit
    runs-on: self-hosted
    container:
      image: rust:1.87-bookworm
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup container environment
        run: |
          apt-get update && apt-get install -y git ca-certificates
          git config --global --add safe.directory /github/workspace

      - name: Run security audit
        run: cargo audit

  check-dependencies:
    name: Check Dependencies
    runs-on: self-hosted
    container:
      image: rust:1.87-bookworm
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup container environment
        run: |
          apt-get update && apt-get install -y git ca-certificates
          git config --global --add safe.directory /github/workspace

      - name: Check for outdated dependencies
        run: cargo outdated --exit-code 1
        continue-on-error: true

  coverage:
    name: Code Coverage
    runs-on: self-hosted
    container:
      image: rust:1.87-bookworm
      options: --user root
    permissions:
      # Required for OIDC authentication with Codecov
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup container environment
        run: |
          apt-get update && apt-get install -y git ca-certificates build-essential pkg-config libssl-dev
          rustup component add llvm-tools-preview
          git config --global --add safe.directory /github/workspace

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          fail_ci_if_error: false
          use_oidc: true
          # Alternative: For repositories without OIDC support, use token instead:
          token: ${{ secrets.CODECOV_TOKEN }}

  msrv-check:
    name: Minimum Supported Rust Version
    runs-on: self-hosted
    container:
      image: rust:1.87-bookworm
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup container environment
        run: |
          apt-get update && apt-get install -y git ca-certificates build-essential pkg-config libssl-dev
          git config --global --add safe.directory /github/workspace

      - name: Test with MSRV
        run: cargo check --all-features

  documentation:
    name: Documentation
    runs-on: self-hosted
    container:
      image: rust:1.87-bookworm
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup container environment
        run: |
          apt-get update && apt-get install -y git ca-certificates build-essential pkg-config libssl-dev
          git config --global --add safe.directory /github/workspace

      - name: Build documentation
        run: cargo doc --all-features --no-deps

      - name: Check for broken links in docs
        run: cargo doc --all-features --no-deps --document-private-items
