name: Lint and Test

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.90.0"
          rustflags: -D warnings
          components: rustfmt, clippy, llvm-tools-preview

      - name: Install cargo tools
        run: |
          if ! command -v cargo-llvm-cov &> /dev/null; then
            cargo install cargo-llvm-cov
          else
            echo "cargo-llvm-cov already installed"
          fi
          if ! command -v cargo-audit &> /dev/null; then
            cargo install cargo-audit
          else
            echo "cargo-audit already installed"
          fi
          if ! command -v cargo-outdated &> /dev/null; then
            cargo install cargo-outdated
          else
            echo "cargo-outdated already installed"
          fi

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Check for compilation errors
        run: cargo check --all-targets --all-features

      - name: Run Clippy lints
        run: cargo clippy --all-targets --workspace --lib --examples --all-features --tests --benches -- -D warnings

      - name: Run tests
        run: cargo test --all-features --workspace

      - name: Run documentation tests
        run: cargo test --doc --all-features

      - name: Build examples
        run: cargo build --examples --all-features

      - name: Test examples compilation
        run: |
          cargo check --example accounts_example
          cargo check --example chains_example
          cargo check --example checkpoints_example
          cargo check --example network_examples
          cargo check --example tokens_example
          cargo check --example transactions_example

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.90.0"

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-audit
        run: |
          if ! command -v cargo-audit &> /dev/null; then
            cargo install cargo-audit
          else
            echo "cargo-audit already installed"
          fi

      - name: Run security audit
        run: cargo audit

  check-dependencies:
    name: Check Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.90.0"

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-outdated
        run: |
          if ! command -v cargo-outdated &> /dev/null; then
            cargo install cargo-outdated
          else
            echo "cargo-outdated already installed"
          fi

      - name: Check for outdated dependencies
        run: cargo outdated --exit-code 1
        continue-on-error: true

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    permissions:
      # Required for OIDC authentication with Codecov
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.90.0"

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          fail_ci_if_error: false
          use_oidc: true
          # Alternative: For repositories without OIDC support, use token instead:
          token: ${{ secrets.CODECOV_TOKEN }}

  msrv-check:
    name: Minimum Supported Rust Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.90.0"

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Test with MSRV
        run: cargo check --all-features

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.90.0"

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build documentation
        run: cargo doc --all-features --no-deps

      - name: Check for broken links in docs
        run: cargo doc --all-features --no-deps --document-private-items
